extend: "base.yaml"
data:
  base_folder: /homes/pmcd/Peter_Patrick3
  splits:
      - test
      - train
      - val
  train: train
  test: test
  val: val

model: UNet

fit:
  batch_size: 111
  loss: 
    name: SparseCategoricalCrossEntropy
    from_logits: True
  