extend: !extend base.yaml
data:
  base_folder: /homes/pmcd/Peter_Patrick3
  splits:
      - test
      - train
      - val
  train: train
  test: test
  val: val

model:
  name: UNet
  args:
    n_classes: 2
name: base

fit:
  batch_size: 111
  loss: 
    name: SparseCategoricalCrossEntropy
    from_logits: True
  augmentations: [
    # {cls:}
  ]
  