!!extend:./configs/base.yaml
image_size: !!python/list &img_sz [128, 128]
# data:
#   augmentations:
#     [
#       !!python/object:heartnet.augmentation.Elastic2D {
#         alpha: [0, 450],
#         sigma: [20, 30],
#         apply_prob: 0.333,
#       },
#     ]
model:
  model:
    !!python/object:mpunet.models.UNet {
      n_classes: 2,
      dim: 128,
      depth: 4,
      out_activation: softmax,
    }

# fit:
#   batch_size: 111
name: base
